package com.myspace.hasrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class hasRulesBo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("inputValue")
	private java.lang.String inputValue;

	@org.kie.api.definition.type.Label("scoringValue")
	private java.lang.Integer scoringValue;

	@org.kie.api.definition.type.Label("scoreName")
	private java.lang.String scoreName;

	public hasRulesBo() {
	}

	public java.lang.String getInputValue() {
		return this.inputValue;
	}

	public void setInputValue(java.lang.String inputValue) {
		this.inputValue = inputValue;
	}

	public java.lang.Integer getScoringValue() {
		return this.scoringValue;
	}

	public void setScoringValue(java.lang.Integer scoringValue) {
		this.scoringValue = scoringValue;
	}

	public java.lang.String getScoreName() {
		return this.scoreName;
	}

	public void setScoreName(java.lang.String scoreName) {
		this.scoreName = scoreName;
	}

	public hasRulesBo(java.lang.String inputValue,
			java.lang.Integer scoringValue, java.lang.String scoreName) {
		this.inputValue = inputValue;
		this.scoringValue = scoringValue;
		this.scoreName = scoreName;
	}

}